FROM azul/zulu-openjdk-alpine:11 as build
WORKDIR /workspace/app

# Copy the m2 directory if it exists to re-use an external cache.
# The `mvnw` file is also copied so that if an `.m2` directory isn't present
# the command won't fail.
COPY mvnw .m2* /root/.m2/repository/

COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .
COPY src src

RUN ls -la /root/.m2/repository

RUN ./mvnw dependency:go-offline \
	&& ./mvnw process-resources \
	&& ./mvnw package -Dmaven.default-test.skip=true -Dmaven.test.skip=true -DskipTests --no-transfer-progress \
  && mkdir -p extracted && java -Djarmode=layertools -jar target/*.jar extract --destination extracted

FROM azul/zulu-openjdk-alpine:11-jre

VOLUME /tmp

ARG DEPENDENCY=/workspace/app/extracted

COPY --from=build ${DEPENDENCY}/dependencies/ ./
RUN true
COPY --from=build ${DEPENDENCY}/spring-boot-loader/ ./
RUN true
COPY --from=build ${DEPENDENCY}/snapshot-dependencies/ ./
RUN true
COPY --from=build ${DEPENDENCY}/application/ ./

RUN if [ -e "/BOOT-INF/classes/emulatorcert.crt" ]; then cd $JAVA_HOME/lib/security && keytool -importcert -cacerts -storepass changeit -noprompt -alias documentdbemulator -file /BOOT-INF/classes/emulatorcert.crt; fi

ENTRYPOINT ["java","org.springframework.boot.loader.JarLauncher"]

EXPOSE 9000